"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.x
"""
import os
from datetime import timedelta
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9jj5vc5c98$gb%!2_sr)el!61c(s7vch#a&2sz&jz*xn4kcnso')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*']

# Esto es obligatorio en Render para que Django sepa que la conexión es segura (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

# Application definition
INSTALLED_APPS = [
    # 1. Unfold DEBE ir ANTES de django.contrib.admin
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',

    'django.contrib.staticfiles',

    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Third party apps
    'storages',
    'rest_framework',
    'django_filters',
    'django_summernote',
    'corsheaders',
    'rest_framework_simplejwt',

    # Mis Apps
    'productos',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Cors siempre arriba
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise justo después de Security
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=0  # Para SQLite local es mejor no persistir conexiones
    )
}
# WAL mode: solo aplica a SQLite (psycopg2 no acepta estas opciones)
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default']['OPTIONS'] = {
        'timeout': 60,
        'transaction_mode': 'IMMEDIATE',
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES CONFIGURATION ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# --- CLOUDFLARE R2 ---
R2_ACCOUNT_ID        = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID     = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME       = os.environ.get('R2_BUCKET_NAME', '')
R2_PUBLIC_DOMAIN     = os.environ.get('R2_PUBLIC_DOMAIN', '')  # ej: pub-xxx.r2.dev

AWS_ACCESS_KEY_ID       = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY   = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL     = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com'
AWS_S3_REGION_NAME      = 'auto'
AWS_S3_CUSTOM_DOMAIN    = R2_PUBLIC_DOMAIN
AWS_QUERYSTRING_AUTH    = False   # URLs públicas sin firma
AWS_S3_FILE_OVERWRITE   = False   # no sobreescribir archivos con el mismo nombre
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

# --- MEDIA FILES ---
MEDIA_URL = f'https://{R2_PUBLIC_DOMAIN}/' if R2_PUBLIC_DOMAIN else '/media/'

# --- STORAGES ---
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --- WHITENOISE ---
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# --- REST FRAMEWORK & JWT ---
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

# --- CORS ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://decoud-colchones.vercel.app",
]

# En desarrollo (DEBUG=True), permitimos todo para evitar estos problemas de puertos
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- UNFOLD ADMIN ---
UNFOLD = {
    "SITE_TITLE":  "Decoud Admin",
    "SITE_HEADER": "Decoud Colchones",
    "SITE_URL":    "/",
    "SITE_SYMBOL": "bed",          # Google Material Symbol
    "SHOW_HISTORY":      True,
    "SHOW_VIEW_ON_SITE": True,

    # Fuerza modo oscuro antes de que Unfold renderice
    "SCRIPTS": [
        lambda request: static("js/admin_dark.js"),
    ],

    # Colores de la marca — primary = dorado Decoud
    "COLORS": {
        "primary": {
            "50":  "255 251 235",
            "100": "254 243 199",
            "200": "253 230 138",
            "300": "252 211 77",
            "400": "251 191 36",
            "500": "212 175 55",   # dorado Decoud
            "600": "180 148 40",
            "700": "150 120 30",
            "800": "120 95  20",
            "900": "90  70  15",
            "950": "60  45  10",
        },
    },

    # Sidebar con navegación organizada por área
    "SIDEBAR": {
        "show_search":           True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Ventas",
                "separator": True,
                "items": [
                    {
                        "title": "Pedidos",
                        "icon":  "shopping_bag",
                        "link":  reverse_lazy("admin:productos_pedido_changelist"),
                    },
                ],
            },
            {
                "title": "Catálogo",
                "separator": True,
                "items": [
                    {
                        "title": "Productos",
                        "icon":  "bed",
                        "link":  reverse_lazy("admin:productos_producto_changelist"),
                    },
                    {
                        "title": "Categorías",
                        "icon":  "folder_open",
                        "link":  reverse_lazy("admin:productos_categoria_changelist"),
                    },
                    {
                        "title": "Líneas",
                        "icon":  "layers",
                        "link":  reverse_lazy("admin:productos_lineaproducto_changelist"),
                    },
                ],
            },
            {
                "title": "Contenido",
                "separator": True,
                "items": [
                    {
                        "title": "Banners",
                        "icon":  "image",
                        "link":  reverse_lazy("admin:productos_banner_changelist"),
                    },
                ],
            },
            {
                "title": "Administración",
                "separator": True,
                "items": [
                    {
                        "title": "Usuarios",
                        "icon":  "person",
                        "link":  reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
        ],
    },
}

X_FRAME_OPTIONS = 'SAMEORIGIN'
SUMMERNOTE_THEME = 'bs4'

# --- MOBBEX ---
# Credenciales de PRUEBA por defecto. Reemplazar con las reales en producción (.env)
MOBBEX_API_KEY     = os.environ.get('MOBBEX_API_KEY',     'zJ8LFTBX6Ba8D611e9io13fDZAwj0QmKO1Hn1yIj')
MOBBEX_ACCESS_TOKEN = os.environ.get('MOBBEX_ACCESS_TOKEN', 'd31f0721-2f85-44e7-bcc6-15e19d1a53cc')
# True  → ambiente sandbox (test). False → producción real.
MOBBEX_TEST        = os.environ.get('MOBBEX_TEST', 'true').lower() == 'true'

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
# En producción debe ser la URL pública del servidor Django (para el webhook de Mobbex)
BACKEND_URL  = os.environ.get('BACKEND_URL',  'http://localhost:8000')