"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.x
"""
import os
from datetime import timedelta
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9jj5vc5c98$gb%!2_sr)el!61c(s7vch#a&2sz&jz*xn4kcnso')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    # 1. Jazzmin debe ir ANTES de admin
    'jazzmin',
    
    # 2. Cloudinary Storage debe ir ANTES de staticfiles
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Third party apps
    'rest_framework',
    'django_summernote',
    'corsheaders',
    'rest_framework_simplejwt',
    
    # Mis Apps
    'productos',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Cors siempre arriba
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # Aumenté un poco el tiempo para desarrollo
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# CAMBIO: Configuración para Argentina
LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- JAZZMIN SETTINGS ---
JAZZMIN_SETTINGS = {
    "site_title": "Decoud Admin",
    "site_header": "Decoud Colchones",
    "site_brand": "Decoud",
    "site_logo": None, 
    "welcome_sign": "Bienvenido al Panel de Decoud",
    "copyright": "Decoud Colchones Ltd",
    "search_model": "productos.Producto",
    
    # Menú superior
    "topmenu_links": [
        {"name": "Ir a la Web",  "url": "http://localhost:5173", "new_window": True},
    ],

    # --- ICONOS PERSONALIZADOS (FontAwesome) ---
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        
        # Mis Apps
        "productos.Banner": "fas fa-images",        # Icono de Imágenes
        "productos.Producto": "fas fa-bed",         # Icono de Cama
        "productos.Categoria": "fas fa-tags",       # Icono de Etiquetas
        "productos.Pedido": "fas fa-shopping-cart", # Icono de Carrito de Compras
        "productos.VarianteColchon": "fas fa-ruler-combined", # Icono de Regla/Medidas
    },

    # --- ORDEN DEL MENÚ LATERAL ---
    # Ponemos primero los Pedidos y Productos, que es lo que más usará tu amigo
    "order_with_respect_to": [
        "productos.Pedido", 
        "productos.Producto", 
        "productos.Banner", 
        "productos.Categoria",
        "auth"
    ],

    # Tu CSS oscuro personalizado
    "custom_css": "css/dark_mode.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # --- BARRA SUPERIOR (Negra) ---
    "brand_colour": "navbar-dark",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    
    # --- ACENTOS DORADOS (La clave) ---
    # "warning" en Bootstrap es amarillo/dorado. Usamos esto para los detalles.
    "accent": "accent-warning", 
    
    # --- BARRA LATERAL (Negra con letras doradas) ---
    "sidebar": "sidebar-dark-warning", 
    
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True, # Esto hace que los sub-menús se metan un poco a la derecha
    "sidebar_nav_compact_style": False,
    
    "main_bg_color": "#121212",
}

# --- 1. CONFIGURACIÓN DE CLOUDINARY ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'djv3eauty', 
    'API_KEY': '431898246464991', 
    'API_SECRET': 'YQZBe99VVCx0hWldaF0MWwvPZWA',
}

# --- 2. CONFIGURACIÓN DE ALMACENAMIENTO (Django 5) ---
# Esto le obliga a Django a usar Cloudinary para los archivos subidos (media)
# y el sistema local solo para los archivos estáticos (css, js).
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --- 3. URLS ---
MEDIA_URL = '/media/'  # Necesario para que Cloudinary construya el link público
# IMPORTANTE: NO pongas MEDIA_ROOT. Si lo pones, Django podría confundirse.
# AUTH_USER_MODEL = 'users.User'

STATIC_URL = '/static/'

# AGREGAR ESTO SI NO LO TIENES:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Permite que Summernote funcione dentro del admin
X_FRAME_OPTIONS = 'SAMEORIGIN' 

# Configuración opcional para que se vea mejor
SUMMERNOTE_THEME = 'bs4'