# Generated by Django 5.2.8 on 2025-12-03 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='VarianteColchon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.CharField(max_length=50, verbose_name='Altura y Descripción de Cubierta')),
                ('medida', models.CharField(choices=[('80x190', '80x190 cm'), ('100x190', '100x190 cm'), ('140x190', '140x190 cm')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código SKU')),
            ],
            options={
                'verbose_name_plural': 'Variantes de Colchón (SKUs)',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Productos (Líneas)'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad',
            field=models.IntegerField(default=24, verbose_name='Densidad (kg/m³)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_base',
            field=models.TextField(default='Descripción de línea pendiente de actualización.', verbose_name='Materiales/Descripción Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_max_max',
            field=models.IntegerField(default=100, verbose_name='Peso Máximo Soportado (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_max_min',
            field=models.IntegerField(default=70, verbose_name='Peso Mínimo Soportado (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Línea de Colchón'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='variantecolchon',
            name='producto_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='variantecolchon',
            unique_together={('producto_linea', 'altura', 'medida')},
        ),
    ]
