# Generated by Django 5.2.8 on 2026-01-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_destacado_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(default='Santa Fe', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
