# Generated by Django 5.2.8 on 2026-01-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_provincia_pedido_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Texto opcional para referencia', max_length=100)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('orden', models.IntegerField(default=0, help_text='0 va primero, 1 va segundo, etc.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Banners del Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
