# Generated by Django 5.2.8 on 2026-02-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantecolchon',
            options={'verbose_name_plural': 'Variantes'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='variantecolchon',
            name='descripcion_cubierta',
            field=models.CharField(blank=True, help_text='Ej: Tela Jackard Matelaseada', max_length=200, verbose_name='Tela/Cubierta'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='medida_altura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto_linea',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='densidad',
            field=models.CharField(max_length=50, verbose_name='Densidad (ej: 30 kg/m³)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en carrusel/ofertas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_max_max',
            field=models.IntegerField(verbose_name='Peso Máximo (kg)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_max_min',
            field=models.IntegerField(verbose_name='Peso Mínimo (kg)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock General'),
        ),
        migrations.AlterField(
            model_name='variantecolchon',
            name='altura',
            field=models.CharField(max_length=50, verbose_name='Altura (ej: 25 cm)'),
        ),
        migrations.AlterField(
            model_name='variantecolchon',
            name='medida',
            field=models.CharField(choices=[('80x190', '80x190 cm'), ('100x190', '100x190 cm'), ('140x190', '140x190 cm'), ('160x200', '160x200 cm'), ('180x200', '180x200 cm'), ('200x200', '200x200 cm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='variantecolchon',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen Extra',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['orden'],
            },
        ),
    ]
