# Generated by Django 5.2.8 on 2026-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_variantecolchon_options_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cuotas',
            field=models.IntegerField(default=12, verbose_name='Cantidad de Cuotas s/interés'),
        ),
    ]
