# Generated by Django 5.2.8 on 2026-02-03 16:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_cuotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: LINEA DESEO', max_length=100)),
                ('slug', models.SlugField(help_text='Identificador para la URL (ej: deseo, oro, hotel)', unique=True)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='lineas/', verbose_name='imagen')),
                ('orden', models.IntegerField(default=0, help_text='Menor número aparece primero')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Línea de Producto',
                'verbose_name_plural': 'Líneas de Productos',
                'ordering': ['orden'],
            },
        ),
    ]
