# Generated by Django 4.2.28 on 2026-02-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_lineaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='telefono',
            new_name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='medida_altura',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='producto_linea',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='merchant_order_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='apellido_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='dni_cliente',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='Mercado Pago', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variante_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.variantecolchon'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
