# Generated by Django 4.2.28 on 2026-03-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.lineaproducto', verbose_name='Línea'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_top_pillow',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Top Pillow?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='densidad',
            field=models.CharField(max_length=50, verbose_name='Densidad (ej: 28)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_max_max',
            field=models.IntegerField(default=100, verbose_name='Peso Máximo (kg)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_max_min',
            field=models.IntegerField(default=0, verbose_name='Peso Mínimo (kg)'),
        ),
    ]
