# Generated by Django 4.2.28 on 2026-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_producto_options_producto_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='garantia',
            field=models.CharField(choices=[('Sin garantía', 'Sin garantía'), ('1 año', '1 año'), ('2 años', '2 años'), ('3 años', '3 años'), ('4 años', '4 años'), ('5 años', '5 años')], default='1 año', max_length=50, verbose_name='Garantía'),
        ),
    ]
