# Generated by Django 4.2.28 on 2026-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_producto_garantia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantecolchon',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='variantecolchon',
            name='altura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Altura específica (ej: 25 cm)'),
        ),
        migrations.AlterField(
            model_name='variantecolchon',
            name='medida',
            field=models.CharField(choices=[('1 Plaza', '1 Plaza (80x190)'), ('1 1/2 Plaza', '1 1/2 Plaza (100x190)'), ('2 Plazas', '2 Plazas (140/160/180/200)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='variantecolchon',
            unique_together={('producto_linea', 'medida')},
        ),
    ]
