# Generated by Django 4.2.28 on 2026-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_variantecolchon_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='lineaproducto',
            options={'ordering': ['orden'], 'verbose_name': 'Línea de Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-creado_en',), 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Galería de Imágenes'},
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variante_original',
        ),
        migrations.AlterField(
            model_name='lineaproducto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lineaproducto',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineaproducto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cuotas',
            field=models.IntegerField(default=12, verbose_name='Cuotas s/interés'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='densidad',
            field=models.CharField(max_length=50, verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_base',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='garantia',
            field=models.CharField(choices=[('Sin garantía', 'Sin garantía'), ('1 año', '1 año'), ('2 años', '2 años'), ('3 años', '3 años'), ('4 años', '4 años'), ('5 años', '5 años')], default='1 año', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VarianteColchon',
        ),
    ]
