# Generated by Django 4.2.28 on 2026-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(choices=[('1_plaza', '1 Plaza'), ('1_y_media', '1 1/2 Plaza'), ('2_plazas', '2 Plazas')], default='2_plazas', max_length=20, verbose_name='Medida/Plazas'),
        ),
    ]
