# Generated by Django 4.2.28 on 2026-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_producto_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(blank=True, help_text='Solo el número (ej: 25)', null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='densidad',
            field=models.IntegerField(blank=True, help_text='Solo el número (ej: 30)', null=True, verbose_name='Densidad (kg/m³)'),
        ),
    ]
