# Generated by Django 6.0.5 on 2026-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_producto_altura_alter_producto_densidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lineas/'),
        ),
    ]
