# Generated by Django 6.0.6 on 2026-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_lineaproducto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_rotativo',
            field=models.BooleanField(default=True, verbose_name='¿Es rotativo?'),
        ),
    ]
